name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 17]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.0

      - name: Install Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node }}

      - run: yarn install

      - run: yarn lint

      - run: yarn build

      - run: yarn test

      - run: yarn package
        if: ${{ matrix.node != 17 }}

      - run: export NODE_OPTIONS=--openssl-legacy-provider && yarn package
        if: ${{ matrix.node == 17 }}
